#!/bin/sh

ERLANG_VERSION=$(erl -eval 'io:format("~s",[erlang:system_info(otp_release)]), halt().'  -noshell | perl -p -e 's/^R//;' -e 's/B[0-9]+$//;')

DIALYZER_FLAGS="-DTEST=true"
if test "$ERLANG_VERSION" -lt 17; then
  DIALYZER_FLAGS="${DIALYZER_FLAGS} -DOXTHRIFT_NO_MAPS=true"
fi
if test "$ERLANG_VERSION" -ge 18; then
  DIALYZER_FLAGS="${DIALYZER_FLAGS} -DNAMESPACED_TYPES=true"
fi

echo "$DIALYZER_FLAGS"
